### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Lakedaemon** [square/flow#149]
I'm using Flow 0.12 in some production apps.
Apparently, Flow is moving... TreeKeys, MultiKeys, Installing Flow through a Fragment (I thought that the whole point (at start) was to avoid fragments...).
I would like to evaluate if/when I should migrate to the latest Flow code (that seems to bring nice stuff)

Could you please tell us (flow users) : 
Where the flow library is heading ? (is there some kind of design/loose roadmap ?) 
Why you are doing it differently  ?
If/When the present code is usable in production ? 

I see that there are simple sample apps. That's cool. A little introduction to the new flow would be nice too.
 Best regards, 
Olivier

**Comment by loganj** [comment]
Headed for a 1.0 alpha as fast as we can, and a beta after that. Note that nothing on master has seen a release since 0.12-- this is deliberate. If your app is working, I definitely wouldn't migrate before alpha, and likely wouldn't update before beta.

I agree a roadmap is overdue (#151).

There will definitely be an overview/introduction published when we reach 1.0, at the latest. For now I'm concentrating on writing a new README (#142), an exercise that's helping clarify design and API. If you want to see the shape/design of 1.0, keep an eye on the README as it evolves.

**Comment by Lakedaemon** [comment]
Many thanks for the kind and enlightening answer. 
I'll definitely keep an eye on the Readme.
Oh.. and can't wait for the 1.0 release (Flow 0.12 kicked and still kicks a lot of ass for me :)
